version: "3"
# docker pull kibana:8.12.2
services:
  elastic:
    build: .
    image: elasticsearch-ik:8.12.2
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=123456
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - es-network
  kibana:
    container_name: kibana
    image: kibana:8.12.2
    restart: always
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - es-network
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

networks:
  es-network:
    driver: bridge